source 'https://rubygems.org'
ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.4'

gem 'celluloid', '~> 0.15.2'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'reel', '~> 0.4.0'
gem "multi_json", "~> 1.8.4"
gem 'pry'
gem 'encryptor'
